default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DATABASE_NAME", "heco") %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "heco_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "heco_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "heco") %>
