version: "3.8"
services:
  backend:
    build: .
    command: test
    environment:
      - DATABASE_NAME=heco-test
      - DATABASE_USER=heco-test
      - DATABASE_PASSWORD=heco-test
      - DATABASE_HOST=db
      - CLOUD_TASKS_TEST_QUEUE_NAME=test
      - FRONTEND_URL=http://localhost:4000
      - IS_API_INSTANCE=true
      - IS_JOBS_INSTANCE=true
    depends_on:
      - db
  db:
    image: postgis/postgis:14-3.2-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=heco-test
      - POSTGRES_USER=heco-test
      - POSTGRES_PASSWORD=heco-test
