version: "3.8"
services:
  backend:
    build:
      context: .
      args:
        - TRANSIFEX_TOKEN=${TRANSIFEX_TOKEN}
    command: test
    environment:
      - DATABASE_NAME=heco-test
      - DATABASE_USER=heco-test
      - DATABASE_PASSWORD=heco-test
      - DATABASE_HOST=db
    depends_on:
      - db
  db:
    image: postgres:14.2
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=heco-test
      - POSTGRES_USER=heco-test
      - POSTGRES_PASSWORD=heco-test
