source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.0"

gem "rails", "~> 7.0.1"
gem "pg", "~> 1.1"
gem "pg_search"
gem "puma", "~> 5.6"
gem "redis", "~> 4.0"
gem "rswag"
gem "active_storage_validations"
gem "rspec-rails", "~> 5.0.0"

gem "cssbundling-rails"
gem "jsbundling-rails"
gem "sprockets-rails"
gem "stimulus-rails"
gem "turbo-rails"

gem "friendly_id", "~> 5.4.0"
gem "devise"
gem "devise-i18n"
gem "traco"

# API
gem "jsonapi-serializer"
gem "pagy"

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

gem "bootsnap", require: false

gem "cloudtasker", "~> 0.13.0"
gem "google-cloud-storage", "~> 1.36.1", require: false
gem "image_processing", ">= 1.2"
gem "mini_magick"

gem "rgeo"
gem "rgeo-geojson"

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails"
  gem "faker"
  gem "standard"
  gem "dotenv-rails"
end

group :development do
  gem "annotate"

  gem "brakeman", require: false
  gem "bundler-audit", require: false
  gem "letter_opener_web"
  gem "rubocop"
  gem "rubocop-performance"
  gem "web-console"
  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  gem "rspec-collection_matchers"
  gem "rspec-request_snapshot"
  gem "rswag-specs"
  gem "simplecov", require: false
  gem "super_diff"
  gem "test-prof"
end
