import { Languages } from 'enums';

export type Investor = {
  id: string;
  type: 'investor';
  // name: string;
  slug: string;
  picture_url: string;
  // about?: string;
  // website?: string;
  // instagram?: string;
  // facebook?: string;
  // linkedin?: string;
  // twitter?: string;
  // how_do_you_work: string;
  // what_makes_the_difference?: string;
  // other_information: string;
  // investor_type: string;
  categories: string[];
  ticket_sizes: string[];
  instrument_types: string[];
  impacts: string[];
  sdgs: number[];
  review_status: string;
  // previously_invested: boolean;
  // previously_invested_description?: string;
  // language: Languages;
};

export type InvestorForm = {
  language: Languages;
  picture: string;
  name: string;
  about?: string;
  website?: string;
  linkedin?: string;
  facebook?: string;
  twitter?: string;
  instagram?: string;
  investor_type: string;
  how_do_you_work: string;
  what_makes_the_difference?: string;
  other_information: string;
  previously_invested: boolean;
  previously_invested_description?: string;
  contact_email: string;
  contact_phone: string;
  categories: string[];
  ticket_sizes: string[];
  instrument_types: string[];
  impacts: string[];
  sdgs: number[];
};
