// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ShapefileController from "./shapefile_controller.js"
import MenuController from "./menu_controller";
application.register("shapefile", ShapefileController)
application.register("menu", MenuController)
