env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

name: Backend Tests
on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend*'

defaults:
  run:
    working-directory: backend

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgis/postgis:14-3.2-alpine
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports: ["5432:5432"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libpq-dev build-essential libcurl4-openssl-dev libgeos-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: backend
          bundler-cache: true
          cache-version: 2
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install Node Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: ${{ env.POSTGRES_USER }}
          PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}
          CLOUD_TASKS_TEST_QUEUE_NAME: test
        run: |
          bin/rails db:drop db:create db:schema:load
      - name: Run tests
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: ${{ env.POSTGRES_USER }}
          PGPASSWORD: ${{ env.POSTGRES_PASSWORD }}
          CLOUD_TASKS_TEST_QUEUE_NAME: test
          FRONTEND_URL: http://localhost:4000
          IS_API_INSTANCE: true
          IS_JOBS_INSTANCE: true
          ENCRYPTION_PRIMARY_KEY: TEST
          ENCRYPTION_DETERMINISTIC_KEY: TEST
          ENCRYPTION_DERIVATION_SALT: TEST
          KLAB_API_HOST: https://developers.integratedmodelling.org
          KLAB_API_USERNAME: TEST
          KLAB_API_PASSWORD: TEST
        run: bundle exec rspec spec
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots
          path: backend/tmp/screenshots
