name: Push backend translations to Transifex
on:
  push:
    branches:
      - develop
    paths:
      - 'backend/**'
      - '.github/workflows/backend*'

defaults:
  run:
    working-directory: backend

jobs:
  push-translations:
    name: Push backend translations to Transifex
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Transifex CLI
        run: |
          echo 'Installing the Transifex CLI…'
          mkdir tx-cli
          cd tx-cli
          curl -o- https://raw.githubusercontent.com/transifex/cli/v1.0.3/install.sh | bash
          cd ..

      - name: Push source strings to Transifex
        env:
          TRANSIFEX_TOKEN: ${{ secrets.TRANSIFEX_TOKEN }}
          ENV: ${{ inputs.env }}
        run: TX_TOKEN=${{ env.TRANSIFEX_TOKEN }} ./tx-cli/tx push -s
