name: Front-end development deployment
on:
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  deploy:
    name: Deploy to development
    uses: ./.github/workflows/frontend-deployment.yml
    with:
      env: development
      github-comment: true
    secrets:
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
      vercel-team-id: ${{ secrets.VERCEL_TEAM_ID }}
      vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      transifex-token: ${{ secrets.TRANSIFEX_TOKEN }}
