name: Staging deployment
on:
  push:
    branches:
    - develop

jobs:
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create deployment
      uses: bobheadxi/deployments@v0.6.2
      id: deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: staging

    - uses: dorny/paths-filter@v2
      id: filters
      with:
        filters: |
          backend:
            - 'backend/**'
          frontend:
            - 'frontend/**'

    - name: Run front-end tests
      if: steps.filter.outputs.frontend == 'true'
      working-directory: frontend
      run: yarn test

    - name: Front-end deployment
      if: steps.filter.outputs.frontend == 'true'
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        github-comment: false
        vercel-args: '--prod'
        scope: ${{ secrets.VERCEL_TEAM_ID }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} 
        working-directory: ./frontend

    - name: Update deployment status
      uses: bobheadxi/deployments@v0.6.2
      if: always()
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        env_url: https://heco-invest-frontend.vercel.app/
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
